version: '3'
services:
  slack-grand-race:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/go/src/github.com/isfonzar/slack-grand-race
    env_file:
      - .env

  postgres:
    image: postgres:9.6
    ports:
      - '8041:5432'
    env_file:
      - .env
    environment:
      LC_ALL: C.UTF-8
