# Gopkg.toml file
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.5.0"
